spring:
  profiles:
    active:
      - dev
      
---

spring:
  profiles:
    active:
      - dev
      
---
spring:
  profiles: test   # 测试环境
  application:
    name: microservicecloud-config-test

#请保存为UTF-8格式  